### ISSUE TITLE
Unexpected token error with single quote

### ISSUE THREAD

**Issue by guyaumetremblay** [tralves/ns-vue-loader#1]
Hi, 

Don't know if it's related to the loader but I get this error when I put single quote in the declaration of an event like @tap:

```
ERROR in ...
Module parse failed: ...
 Unexpected token (1:838)
You may need an appropriate loader to handle this file type.
```

This fail:

```
<Label text="baz" @tap="foo('bar')"></Label>
```
But this work:
```
<Label text="baz" @tap="foo()"></Label>
```

Thanks

**Comment by tralves** [comment]
It is a bug. Probably not escaping correctly... Should be an easy fix, but I have to see about it tomorrow.

In case, you or someone wants to help, the problem is in [this line](https://github.com/tralves/ns-vue-loader/blob/77e9681b8cbd391490f071ce996f97a860cfce44/lib/template-compiler/index.js#L104).
I have to escape `'` html.

**Comment by tralves** [comment]
@guyaumetremblay solved. Thank you for the report!

**Comment by guyaumetremblay** [comment]
Thanks @tralves ! I'm sorry, I was on the road and miss your answer.
